feat: add model for user, department, and board
Moong-glE/my-community-backend pull request #35
Opened 2020-08-01 09:10 UTC by GunHee5719

review plz!!

@hea9549 @RyuJaesang @hihiboss @als95 @jhcheon1000

2020-08-02 13:22 UTC, hihiboss requested changes

2020-08-02 13:22 UTC, hihiboss commented on mycomm/models.py
> +from django.db import models
mycomm 안에 모든 모델이 다 들어가는게 아니라 board 어플리케이션, department 어플리케이션, user 어플리케이션 등으로 나누어 각 어플리케이션의 `models.py` 안에 모델을 정의해야 할 것 같습니다.

이부분은 장고 컨벤션이라 @hea9549 님의 리뷰가 필요합니다 :)

2020-08-02 13:22 UTC, hihiboss commented on mycomm/models/board.py
> +        verbose_name='익명기능 존재여부',
**suggestion**: `익명여부` 가 더 간결하고 직관적이라고 생각되어 제안합니다.

```suggestion
        verbose_name='익명여부',
```

2020-08-02 13:22 UTC, hihiboss commented on mycomm/models/board.py
> +        verbose_name='학과 이름',
**suggestion**: 학과의 이름을 나타내는 것이 아닌 학과와의 연관이므로 다음을 제안합니다.
```suggestion
        verbose_name='학과',
```

2020-08-02 13:22 UTC, hihiboss commented on mycomm/models/board.py
> +        verbose_name='그룹 이름',
**suggestion**: 그룹의 이름을 나타내는 것이 아닌 그룹과의 연관이므로 다음을 제안합니다.
```suggestion
        verbose_name='그룹',
```

2020-08-02 13:22 UTC, hihiboss commented on mycomm/models/board.py
> +        related_name='user_manage_board'
**suggestion**: 연관 테이블의 이름이 엔티티-엔티티가 아니라 엔티티-동사-엔티티라 어색합니다. 다음을 제안합니다.
```suggestion
        related_name='manager_board'
```

2020-08-02 13:22 UTC, hihiboss commented on mycomm/models/user.py
> +        on_delete=models.CASCADE,
**suggestion**: 학과가 삭제되어도 유저는 삭제되지 않아야하므로 CASCADE 대신 SET_NULL을 제안합니다.

2020-08-02 13:35 UTC, GunHee5719 commented on mycomm/models/board.py
> +        verbose_name='학과 이름',
이부분 @jhcheon1000 의 아이디어인데, 학과 id와 연관되는 외래키 이므로 `학과 Id` 로 연관하는건 어떤가요?

2020-08-02 14:09 UTC, hihiboss commented on mycomm/models/board.py
> +    managerIds = models.ManyToManyField(
**suggestion**: managerIds 대신 managers 혹은 manager_list를 제안합니다.

2020-08-02 14:09 UTC, hihiboss commented on mycomm/models/board.py
> +    isHidden = models.BooleanField(
**suggestion**: 파이썬 컨벤션에 따라 is_hidden을 제안합니다.

2020-08-02 14:09 UTC, hihiboss commented on mycomm/models/user.py
> +    studentId = models.CharField(
**suggestion**: 파이썬 컨벤션에 따라 student_id를 제안합니다.

2020-08-02 14:09 UTC, hihiboss commented on mycomm/models/user.py
> +    profileImage = models.ImageField(
**suggestion**: 파이썬 컨벤션에 따라 profile_image를 제안합니다.

2020-08-02 14:31 UTC, hihiboss commented
thought: mycomm 안에 모든 모델이 다 들어가는게 아니라 board 어플리케이션, department 어플리케이션, user 어플리케이션 등으로 나누어 각 어플리케이션의 models.py 안에 모델을 정의해야 할 것 같습니다.

이부분은 장고 컨벤션이라 @hea9549 님의 리뷰가 필요합니다 :)

2020-08-02 14:33 UTC, hihiboss commented on mycomm/models/board.py
> +    managerIds = models.ManyToManyField(
**suggestion**: managers 혹은 manager_list를 제안합니다.

2020-08-02 15:33 UTC, hea9549 requested changes

2020-08-02 15:33 UTC, hea9549 commented on mycomm/models.py
> +from django.db import models
그게 약간 MSA 느낌으로 가는건데 (각 어플리케이션 빼는거)

컨벤션이라기보단, 정하기나름! 둘다 쓰는케이스있어요

그런데 지금 각 모델의 서비스가 크지않을 것 같아
소규모, 처음시작은 models로 모는게 편하고 배우는데 나을듯해서 이렇게가재했엇어욤

나중에 기회되면 리팩하고, 지금은 models로 모는걸로 갑시다~

2020-08-02 15:33 UTC, hea9549 commented on mycomm/models.py
> +from django.db import models
@GunHee5719 그리고 models folder 를 만들었으니 models.py는 없애도될것같아요

2020-08-02 15:33 UTC, hea9549 commented on mycomm/models/board.py
> +    ishidden = models.BooleanField(
```suggestion
    is_hidden = models.BooleanField(
```

2020-08-02 15:33 UTC, hea9549 commented on mycomm/models/board.py
> +    )
default로 false 주는거도 나쁘지않을듯해요

2020-08-02 15:33 UTC, hea9549 commented on mycomm/models/department.py
> +        null=False
blank=False도 추가부탁해여!

2020-08-02 15:33 UTC, hea9549 commented on mycomm/models/department.py
> +        null=False
blank=False도 추가부탁해여!

2020-08-02 15:33 UTC, hea9549 commented on mycomm/models/user.py
> +        unique=True
유니크값으로 주면안될듯

A학교 20192782와 B학교 20192782가 존재할수있음!

2020-08-02 15:33 UTC, hea9549 commented on mycomm/models/user.py
> +        unique=True
유니크로 주고싶으면 유니크를 department, student_id를 묶어서 유니크로 줘야하는데 pair로 unique 할당하는걸로 검색하면 나올듯해요~

2020-08-03 04:05 UTC, GunHee5719 commented
@hihiboss @hea9549 

코멘트 반영했고, 추가로 `user.py` 에서  `email` , `student_id` 필드에도 blank 옵션을 줬는데, 확인 부탁드려요

`unique_together = ('student_id', 'department')` 로 pair unique 옵션을 줬는데, 잘 작동할라나 모르겠네요 테스트를 못해봐서ㅠ

다른분들도 리뷰 부탁해용 @RyuJaesang @als95 @jhcheon1000

2020-08-03 16:15 UTC, hihiboss commented on mycomm/models/user.py
> +        unique_together = ('student_id', 'department')
**thought**: 학과에 가입하지 않은 회원은 department가 null이기 때문에 unique하면 안될 것 같습니다.

2020-08-03 16:15 UTC, hihiboss commented on mycomm/models/user.py
> +        unique=True
**thought**: 저희 서비스가 이메일 인증 같은 절차가 없기 때문에 unique 옵션은 위험해보입니다. 만약, 다른 사람의 이메일로 입력하여 가입하면 다른 사람은 자신의 이메일로 가입하지 못하는 상황이 발생할 수 있을 것 같아서요.

2020-08-04 08:25 UTC, GunHee5719 commented on mycomm/models/user.py
> +        unique_together = ('student_id', 'department')
문득 생각이 드는데 학번에 null=True 옵션을 주고 최초 가입 시에는 null로 설정한 후에, 학과 연동 시에 학번을 입력하여 unique_together 옵션을 가져가는 게 낫지 않을까 생각이 듭니다.

예를 들어 편입을 하는 경우 : '학과 연동 해제 후 새로운 학교에 재연동하고, 학번은 마이페이지에서 별도로 수정' 하는 Flow보다는, '학과 연동 해제 시 학번 정보도 자동으로 null로 설정되고, 학과 연동 시 학번을 입력' 하는게 좋지 않을까요?

2020-08-04 08:27 UTC, GunHee5719 commented on mycomm/models/user.py
> +        unique=True
이메일 인증 진행하는거 아니였나요?? 이메일 인증 없이 형식만 이메일이라면 로그인 옵션에 이메일을 이용하는 이유가 없지 않나요? 그리고 비밀번호 재설정과 같은 기능 이용 시에 이메일 인증 없이 이용하면 위험할 것 같습니다.

2020-08-06 18:07 UTC, hihiboss commented on mycomm/models/user.py
> +        unique_together = ('student_id', 'department')
그런데 학번과 학과에 unique 옵션을 주면 문제가 발생할 것 같습니다.

1. 학번이 null 일 경우, 학과가 같은 회원은 존재할 수 없다 -> 학번이 없고 학과에 가입될 수 있는 회원은 오직 1명만 존재할 수 있음.
(그러나 학과에 가입된 회원이 학번이 없다는 것은 예외 케이스이므로 고려하지 않아도 될듯)

2. 학과가 null 일 경우, 학번이 같은 회원은 존재할 수 없다 -> 학과에 가입하지 않은 회원이 어떤 학번을 선점하면 다른 회원은 그 학번을 설정할 수 없음.

위와 같은 문제가 발생할 수 있을 것 같습니다.

예로 들어준 편입의 경우: `학과 연동 해제 시` -> 학과는 null이 됨 -> 만약 동일한 학번을 가진 학과에 포함되지 않은 회원이 있다면 제약 조건이 위배됨 / `학번 정보도 자동으로 null로 설정` -> 학과도 null 학번도 null 인 회원이 됨 -> 학번과 학과가 없는 회원은 오직 1명일 수 밖에 없음 -> 제약 조건 위배됨

위의 문제가 발생할 수 있을 것 같습니다.

2020-08-06 18:09 UTC, hihiboss commented on mycomm/models/user.py
> +        unique=True
아 이메일 인증까지 구현하는거였나요??

비밀번호 재설정 같은 경우에는 그래서 인증을 통한 재설정이 아닌 저희가 임의로 비밀번호 재설정 후 해당 임시비밀번호를 해당 이메일로 전송하는 것으로 기억해서;;

이메일 인증까지 구현한다면 상관없을 것 같습니다~

2020-08-07 05:29 UTC, hea9549 commented on mycomm/models/user.py
> +        unique=True
넵 이메일인증이 장고에서 지원되는게있어 생각보다 간단하게구현댐니다!

2020-08-07 05:31 UTC, hea9549 commented on mycomm/models/user.py
> +        unique_together = ('student_id', 'department')
넵 여러모로 두개의 unique제약조건은 db단 말고 코드단으로 내리면 좋을듯합니다.

2020-08-07 05:33 UTC, hea9549 reviewed
unique together 제약만풀리면 머지해도될듯합니다 :)

2020-08-07 07:57 UTC, GunHee5719 commented on mycomm/models/user.py
> +        unique_together = ('student_id', 'department')
@hihiboss 넵 둘 다 null인 케이스를 고려했을 때 @hea9549 의견처럼 DB단이 아닌, 프론트에서 검증하는 것이 좋을 것 같긴 하네요. 적용하겠습니당~

2020-08-08 04:31 UTC, hihiboss approved these changes
LGTM

2020-08-08 04:49 UTC, hihiboss commented
**check**: 학과 혹은 그룹이 삭제되면 게시판, 게시글도 모두 삭제되는걸로 의도하신게 맞죠?!

2020-08-08 06:16 UTC, GunHee5719 commented
> **check**: 학과 혹은 그룹이 삭제되면 게시판, 게시글도 모두 삭제되는걸로 의도하신게 맞죠?!

넵 맞습니당~~

2020-08-08 07:14 UTC, als95 commented on mycomm/models/user.py
> +        default=False
is_active라 default를 True로 하는 것이 더 맞다고 생각합니다!

2020-08-08 07:44 UTC, GunHee5719 commented on mycomm/models/user.py
> +        default=False
아. 맞네요!

2020-08-08 07:47 UTC, pingoo33 approved these changes

2020-08-10 12:26 UTC, hea9549 approved these changes

2020-08-10 12:37 UTC, merged