feat:add model for vote, voteanswer
Moong-glE/my-community-backend pull request #39
Opened 2020-08-02 12:47 UTC by jhcheon1000

Vote 및 VoteAnswer 모델 추가.

plz review.
@hea9549 @RyuJaesang @GunHee5719 @hihiboss @als95

2020-08-02 13:14 UTC, GunHee5719 commented on mycomm/models/vote.py
> +    article = models.OneToOneField(
이거 찾아보니깐 OneToOneField 랑 ForeignKey랑 같은 개념이긴 한데

OneToOneField -> 역참조 시 객체 반환
ForeignKey -> 역참조 시 쿼리셋 반환

이 차이라고 하는데, 1:N관계에서는 ForeignKey를 쓰니깐 통일성을 위해 N:N 필드 외의 참조값들은 ForeignKey로 통일하는게 맞을지, 아니면 1:1에서는 OneToOneField로 정의하는게 맞을지 생각해봐야 할듯 합니다.

@hihiboss @jhcheon1000 @hea9549 @RyuJaesang @als95

2020-08-02 13:14 UTC, GunHee5719 commented on mycomm/models/vote.py
> +        verbose_name='투표 항목들',
`verbose_name = '투표 항목 리스트'` 로 리스트임을 언급해주는게 더 좋을거같아요

2020-08-02 13:14 UTC, GunHee5719 commented on mycomm/models/voteanswer.py
> +        verbose_name='답변들',
이거도 `verbose_name='답변 리스트'`가 좋을 것 같습니다

2020-08-02 14:00 UTC, hihiboss requested changes

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/vote.py
> +class Vote(models.Model):
**request**: Vote의 ID 필드가 빠졌습니다. 추가 부탁드립니다.

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/vote.py
> +    article = models.OneToOneField(
셋 자체가 '다수가 될 수 있다' 라는 의미를 포함하지만 1:1 관계에서는 성립하지 않으므로 쿼리셋 반환은 객체 반환보다 조금 어색하다고 생각합니다.

더불어, OneToOneField 내에 unique 특성도 포함되어 있기 때문에 1:1 관계를 ForeignKey보다 견고하게 제약할 수 있을 것 같다고 생각됩니다.

따라서 저는 OneToOneField가 더 적합하다고 생각합니다 :)

--
https://whatisthenext.tistory.com/118
위 링크의 예시처럼 실제로 사용할 때 ForeignKey를 사용하면 리턴된 set에서 요소에 다시 접근해야하는 번거로움도 있을 것 같네요.

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/vote.py
> +        verbose_name='게시글 ID',
**suggestion**: ID가 아닌 연관된 게시글 자체에 대한 필드이므로 다음을 제안합니다.
```suggestion
        verbose_name='게시글',
```

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/vote.py
> +    answerIds = models.ForeignKey(
**suggestion**: answerIds는 따로 필드 정의하지 않아도 조회 가능합니다. 
(1:N에서 1에서만 FK 명시하면 됨)

따라서, answerIds 필드 삭제를 제안합니다.

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/vote.py
> +    answerItems = models.CharField(
**request**: CharField가 아닌 ListCharField를 사용해야 합니다.

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/voteanswer.py
> +class VoteAnswer(models.Model):
**request**: VoteAnswer 객체의 ID 필드가 빠졌습니다.

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/voteanswer.py
> +        verbose_name='투표에 답변한 사용자 ID',
**suggestion**: ID값 리턴이 아닌 객체 리턴이기 때문에 '투표에 답변한 사용자'를 제안합니다.

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/voteanswer.py
> +        on_delete=models.CASCADE,
**thought**: 전략을 생각해봅시다.

만약 사용자가 탈퇴했을때 vote의 answer도 삭제할거라면 CASCADE를, 아니라면 SET_NULL을 사용해야 할 것 같습니다.

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/voteanswer.py
> +        verbose_name='답변에 대한 투표 ID',
**suggestion**: ID값 리턴이 아닌 객체 리턴이기 때문에 '답변에 대한 투표'를 제안합니다.

2020-08-02 14:00 UTC, hihiboss commented on mycomm/models/voteanswer.py
> +    answers = models.CharField(
**request**: CharField가 아닌 ListCharField를 사용해야 합니다.

2020-08-02 14:08 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +    article = models.OneToOneField(
저도 찾아보니 ForeignKey에 unique=True 옵션을 줬을 때 OneToOneField와 같은 의미로 쓰일 수 있네요.

제가 찾은 관련 정보는 2가지인데요,

1.
ForeignKey(SomeModel, unique=True)를 사용했을 때, 다음과 같은 warning이 일어남.

    ForeignKey(unique=True) is usually better served by a OneToOneField.

2.
https://stackoverflow.com/questions/5870537/whats-the-difference-between-django-onetoonefield-and-foreignkey

OneToOneField를 사용할 시, RelatedObjectDoesNotExist Exception이 발생할 수 있음.
하지만 ForeignKey를 사용할 시, 빈 쿼리셋만을 반환함.

결국 역관계 참조 발생 여부에 따라 어떤 것을 사용해야할지 정해야할 것 같습니다.

다들 의견 주세용!

2020-08-02 14:18 UTC, hihiboss commented on mycomm/models/vote.py
> +    article = models.OneToOneField(
@jhcheon1000 

예외 발생같은 경우 예외처리 할 수 있지만 빈 쿼리셋의 경우는 쿼리셋이 비었는지를 저희가 다 검사해야하기 때문에 예외가 낫다고 생각합니다.

역관계 참조 발생은 다음처럼
![image](https://user-images.githubusercontent.com/34789831/89125022-5e851c00-d516-11ea-97af-9589dca3dbe4.png)

2020-08-02 14:20 UTC, jhcheon1000 commented on mycomm/models/voteanswer.py
> +        verbose_name='답변에 대한 투표 ID',
다시 보니 voteanswer의 vote는 ForeignKey인 것 같은데, 제 생각이 맞을까요? @hihiboss

2020-08-02 14:26 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +    article = models.OneToOneField(
https://stackoverflow.com/questions/3221745/django-when-extending-user-better-to-use-onetoonefielduser-or-foreignkeyuse?noredirect=1&lq=1

이런 내용도 있는데 다들 읽어보시고 생각 말씀해주세요.

2020-08-02 14:26 UTC, hihiboss commented on mycomm/models/vote.py
> +    article = models.OneToOneField(
@jhcheon1000 

역관계 참조 발생에 따른 처리는 

1. 쿼리셋이 비어있는지 검증
2. 예외 처리 

를 어떻게 구현하느냐에 따라 다르기 때문에 구현하는 사람이 정하면 될 것 같습니다.

그러나 아래와 같은 이유로 예외 처리가 조금 더 편하지 않을까 생각합니다.
> --
> https://whatisthenext.tistory.com/118
> 위 링크의 예시처럼 실제로 사용할 때 ForeignKey를 사용하면 리턴된 set에서 요소에 다시 접근해야하는 번거로움도 있을 것 같네요.

2020-08-02 14:27 UTC, hihiboss commented on mycomm/models/voteanswer.py
> +        verbose_name='답변에 대한 투표 ID',
@jhcheon1000 FK가 맞는 것 같네요 :)

2020-08-02 14:54 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +    article = models.OneToOneField(
@hea9549 @RyuJaesang @als95
다른 분들은 어떻게 생각하시나요?

2020-08-03 04:15 UTC, GunHee5719 commented on mycomm/models/vote.py
> +    answerItems = models.ListCharField(
snake 표기법 따라서 `answer_items` 가 맞을 것 같은데, 프로젝트 전체적인 통일을 하는 느낌으로 ManyToManyField인 경우 's', 'es' 를 붙여 복수형으로 표기하고, ListCharField인 경우 `answer_item_list` 와 같이 list임을 명시하는건 어떨까요?

@hihiboss @hea9549 @RyuJaesang @als95 의견 부탁드려요

2020-08-03 04:15 UTC, GunHee5719 commented on mycomm/models/voteanswer.py
> +    answers = models.ListCharField(
이거도 개인적으로는 list 필드임을 명시하기에 `answer_list` 가 좋을 것 같습니다.

2020-08-03 04:15 UTC, GunHee5719 commented on mycomm/models/vote.py
> +    expiredAt = models.DateTimeField(
`expired_at` 수정해주세용

2020-08-03 04:15 UTC, GunHee5719 commented on mycomm/models/vote.py
> +    isExpired = models.BooleanField(
`is_expired` 수정해주세요

2020-08-03 04:16 UTC, GunHee5719 commented
그리고 혹시.. 해결된 코멘트는 resolve 부탁해요ㅠ.ㅠ

2020-08-03 05:32 UTC, hea9549 commented on mycomm/models/vote.py
> +    article = models.OneToOneField(
one to one 후 예외처리가 바람직할듯합니다 :)

2020-08-03 05:36 UTC, hea9549 requested changes

2020-08-03 05:36 UTC, hea9549 commented on mycomm/models/vote.py
> +        verbo트se_name='투표 항목 리스트',
```suggestion
        verbose_name='투표 항목 리스트',
```
typo error

2020-08-03 05:36 UTC, hea9549 commented on mycomm/models/vote.py
> +    answerItems = models.ListCharField(
```suggestion
    answer_items = models.ListCharField(
```

camelcase -> snake case
모든 필드에 적용해주세요

2020-08-03 12:32 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +    answerItems = models.ListCharField(
@GunHee5719 
verbose_name에서 명시해주니 표기법에 따라 작성하는게 좋다고 생각합니다!

2020-08-03 16:17 UTC, hihiboss commented on mycomm/models/vote.py
> +    answerItems = models.ListCharField(
@GunHee5719 동의합니다.

2020-08-08 04:54 UTC, hihiboss requested changes
@GunHee5719 @hea9549 코멘트 모두 반영하면 저는 어프루브 할게요~

2020-08-11 13:28 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +        verbo트se_name='투표 항목 리스트',
간단한 거니 걍 제가 resolve 하겟습니당. 아래것도 마찬가지요~

2020-08-11 13:29 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +    answerItems = models.ListCharField(
변경하였습니다. 이미 정해진 사항이니 제가 resolve 하겠습니다. 아래것도 마찬가지입니다!

2020-08-11 13:33 UTC, GunHee5719 commented on mycomm/models/vote.py
> +        null=False
`blank=False` 옵션도 넣어주세요

2020-08-11 13:33 UTC, GunHee5719 commented on mycomm/models/vote.py
> +        auto_now_add=False,
`auto_now` 옵션과 `auto_now_add` 옵션은 default value가 False인 것 같아서 개인적으로는 `survey.py` 에서의 `expired_at` 변수와 통일을 위해 삭제하는 것이 좋을 것 같은데, 어떻게 생각하시나요

@jhcheon1000 @hihiboss @als95 @RyuJaesang @hea9549

2020-08-11 13:33 UTC, GunHee5719 commented on mycomm/models/vote.py
> +        null=False
`default=False` 옵션 추가해주세요

2020-08-11 13:33 UTC, GunHee5719 commented on mycomm/models/voteanswer.py
> +        verbose_name='답변에 대한 투표',
개인 취향일 것 같은데, 이 역시 `survey_answer.py` 에서의 `question` 과 통일성 면도 있고, `verbose_name=투표` 만 해도 의미 전달이 괜찮지 않을까 싶습니다. 이 부분은 수정 권유까진 아니라, 고려해봐주세요

2020-08-11 13:37 UTC, RyuJaesang reviewed
전반적으로 verbose name의 간소화가 필요해보입니다.
건희도 이러한 내용을 요지로 리뷰하는 것 같은데 저 또한 추후 개발 편의성을 위해 verbose name의 간소화를 지향하고 싶습니다 :)

2020-08-11 13:37 UTC, RyuJaesang commented on mycomm/models/vote.py
> +        verbose_name='투표 제목',
제가 건희한테 리뷰 받았던 부분인데
투표 모델 안이니 제목 또는 이름으로 해도 좋을 것 같습니다.

2020-08-11 13:43 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +        auto_now_add=False,
제가 삭제하는게 효율적일 것 같습니다~ 있으나 없으나 큰 차이 없을 것도 같고요.

2020-08-11 13:46 UTC, RyuJaesang reviewed
Verbose Name에 관해서 논의해보아요~
@jhcheon1000 @hea9549 @GunHee5719 @hihiboss @als95

2020-08-11 13:46 UTC, RyuJaesang commented on mycomm/models/vote.py
> +        auto_now_add=False,
저도 동의합니다

2020-08-11 13:46 UTC, RyuJaesang commented on mycomm/models/vote.py
> +        verbose_name='투표 기간 만료 일시',
verbose name의 간소화를 위해 '만료 일시'를 제안합니다.
Vote모델 내부 속성이기에 오해의 소지가 없을 것이라 생각합니다.

2020-08-11 13:46 UTC, RyuJaesang commented on mycomm/models/vote.py
> +        verbose_name='투표 기간 만료 여부',
verbose name의 간소화를 위해 '만료 여부'를 제안합니다.
Vote모델 내부 속성이기에 오해의 소지가 없을 것이라 생각합니다.

2020-08-11 13:46 UTC, RyuJaesang commented on mycomm/models/vote.py
> +        verbose_name='투표 항목 리스트',
verbose name의 간소화를 위해 '항목'를 제안합니다.
Vote모델 내부 속성이기에 오해의 소지가 없을 것이라 생각합니다.

2020-08-11 13:46 UTC, RyuJaesang commented on mycomm/models/voteanswer.py
> +        verbose_name='투표에 답변한 사용자',
verbose name의 간소화를 위해 '답변자'를 제안합니다.
Vote모델 내부 속성이기에 오해의 소지가 없을 것이라 생각합니다.

2020-08-11 13:49 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +        verbose_name='투표 항목 리스트',
리스트임을 명시해주시기 위해 절충안으로 '항목 리스트'는 어떤가요?

2020-08-11 13:51 UTC, RyuJaesang commented on mycomm/models/vote.py
> +        verbose_name='투표 항목 리스트',
네 전 동의합니당~! 👍

2020-08-11 13:57 UTC, jhcheon1000 reviewed
아하 이렇게 되는 구만

2020-08-11 13:57 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +from mycomm.models.article import Article
리뷰 실험

2020-08-11 13:57 UTC, jhcheon1000 commented on mycomm/models/vote.py
> +        null=False
실험1

2020-08-11 13:57 UTC, jhcheon1000 commented on mycomm/models/voteanswer.py
> +
실험2

2020-08-13 07:52 UTC, GunHee5719 approved these changes
LGTM:)

2020-08-13 09:06 UTC, hea9549 approved these changes
LGTM

2020-08-13 17:17 UTC, hihiboss approved these changes
LGTM :)

2020-08-16 07:28 UTC, merged