feat: Add article, article file, comment model
Moong-glE/my-community-backend pull request #41
Opened 2020-08-03 12:15 UTC by als95

많은 리뷰 부탁드립니다.

@hea9549 @RyuJaesang @GunHee5719 @jhcheon1000

2020-08-03 12:50 UTC, GunHee5719 requested changes

2020-08-03 12:50 UTC, GunHee5719 commented on mycomm/models/article.py
> +        verbose_name="게시물 제목",
Class 명이 Article 이므로, 간단하게 `verbose_name = '제목'` 으로 해도 괜찮을 것 같습니다.

2020-08-03 12:50 UTC, GunHee5719 commented on mycomm/models/article.py
> +        verbose_name="게시물 좋아요",
좋아요 기능을 이용한 사용자에 대한 컬럼이므로, `verbose_name='좋아요 선택 유저'` 와 같이 유저임을 언급하는게 좋을 것 같습니다.

2020-08-03 12:50 UTC, GunHee5719 commented on mycomm/models/article.py
> +        verbose_name="작성된 게시물의 게시판",
여기도, 간단하게 `게시판` 만 입력해도 될 것 같습니다.

2020-08-03 12:50 UTC, GunHee5719 commented on mycomm/models/article_file.py
> +class ArticleFile(models.Model):
Class명은 혹시 snake 표기법 안따라도 되나요? 파이썬 컨벤션을 자세히 몰라서..

2020-08-03 12:50 UTC, GunHee5719 commented on mycomm/models/article.py
> +        on_delete=models.CASCADE,
회의가 필요한 부분 같은데, 유저가 삭제되었을 때 게시글을 함께 삭제할지, 혹은 삭제된 유저로 게시글은 보관할지에 따라 SET_NULL을 이용하는 부분을 고려해야 할 것 같습니다.

2020-08-03 12:55 UTC, als95 commented on mycomm/models/article_file.py
> +class ArticleFile(models.Model):
네! Class명은 카멜로 합니다!

2020-08-03 13:00 UTC, als95 commented on mycomm/models/article.py
> +        on_delete=models.CASCADE,
다른분들은 어떻게 생각하시나요??

@hea9549 @hihiboss @RyuJaesang @jhcheon1000

2020-08-03 16:29 UTC, hihiboss requested changes

2020-08-03 16:29 UTC, hihiboss commented on mycomm/models/article.py
> +        default='NOTICE',
**suggestion**: default 값은 NORMAL이 더 자연스럽지 않을까요?

2020-08-03 16:29 UTC, hihiboss commented on mycomm/models/article.py
> +        on_delete=models.CASCADE,
저도 @GunHee5719 의견에 동의합니다만, 이야기해보면서 조율해야할 것 같습니다. 이슈 등록해주세요!

2020-08-03 16:29 UTC, hihiboss commented on mycomm/models/article.py
> +        on_delete=models.CASCADE,
**question**: ManyToManyField에 on_delete 옵션이 있나요??

**request**: 좋아요를 누른 사용자가 삭제되어도 게시글은 남아있어야 하기 때문에 CASCADE 는 적절하지 않은 것 같습니다.

2020-08-03 16:29 UTC, hihiboss commented on mycomm/models/comment.py
> +        blank=False
**question**: 빈 댓글은 허용안하는거죠?

2020-08-03 16:29 UTC, hihiboss commented on mycomm/models/comment.py
> +        on_delete=models.CASCADE,
question: ManyToManyField에 on_delete 옵션이 있나요??

request: 좋아요를 누른 사용자가 삭제되어도 댓글은 남아있어야 하기 때문에 CASCADE 는 적절하지 않은 것 같습니다.

2020-08-04 08:50 UTC, GunHee5719 commented on mycomm/models/comment.py
> +        on_delete=models.CASCADE,
상위 댓글이 삭제되었을 때, 하위 댓글을 남길 지에 대한 전략도 고려해봐야 할 것 같습니다. 기존 동문 네트워크 서비스에서는, 원 댓글이 삭제되더라도 하위 댓글들은 보존하는 전략을 채용했습니다. (원 댓글은 "삭제된 댓글입니다" 로 프론트에서 처리)

2020-08-04 08:50 UTC, GunHee5719 commented on mycomm/models/comment.py
> +        related_name="user_comment"
통일되게, `related_name="writer_comment"`가 좋을 것 같습니다. 근데 대부분 예제에서 따옴표를 쓰던데, 쌍따옴표를 써도 되나요? 혹시 모르기도 하고, 다른 파일들에서 따옴표를 쓰도록 커밋 하였으니 통일해주시면 좋을 것 같아요.

2020-08-04 09:09 UTC, als95 commented on mycomm/models/comment.py
> +        related_name="user_comment"
파이썬에서 따옴표와 쌍따옴표 차이는 없습니다. 똑같이 스트링으로 인식합니다!
확인해보니 PEP 8에서 명시된 별다른 컨벤션이 없었습니다.

말씀해주신대로 다른 파일과 동일한 코드 스타일로 바꾸도록 하겠습니다!

2020-08-04 09:10 UTC, als95 commented on mycomm/models/comment.py
> +        blank=False
네! 개인적인 생각으로는 빈 댓글은 허용하면 안될것 같습니다.

2020-08-04 09:11 UTC, als95 commented on mycomm/models/comment.py
> +        on_delete=models.CASCADE,
이부분도 이슈에 같이 올려놓겠습니다! :)

2020-08-08 05:16 UTC, hihiboss requested changes

2020-08-08 05:16 UTC, hihiboss commented on mycomm/models/article.py
> +        on_delete=models.CASCADE,
@als95 

#43 에 따라 수정 부탁드립니다!

2020-08-08 05:16 UTC, hihiboss commented on mycomm/models/comment.py
> +        on_delete=models.SET_NULL,
**thought**: 얘네는 parent 삭제되면 대댓글도 CASCADE로 삭제되는게 맞지 않나여?

2020-08-08 05:54 UTC, als95 commented on mycomm/models/comment.py
> +        on_delete=models.SET_NULL,
#43 에서 같이 의견을 나누었었는데, parent가 삭제되면 삭제된 댓글로 표시하는 의견이 많아 수정했습니다!

2020-08-08 06:03 UTC, als95 commented on mycomm/models/comment.py
> +        on_delete=models.SET_NULL,
parent만 삭제된 댓글로 표시하고 하위 댓글을 남겨두자는 의견이었습니다!

2020-08-08 06:04 UTC, als95 commented on mycomm/models/article.py
> +        on_delete=models.CASCADE,
수정했습니다 :)

2020-08-08 06:42 UTC, hihiboss approved these changes
LGTM

2020-08-08 09:23 UTC, als95 commented on mycomm/models/article.py
> +        verbose_name="작성된 게시물의 게시판",
수정했습니다! :)

2020-08-08 09:23 UTC, als95 commented on mycomm/models/article.py
> +        verbose_name="게시물 좋아요",
수정했습니다! :)

2020-08-08 09:23 UTC, als95 commented on mycomm/models/article.py
> +        verbose_name="게시물 제목",
수정했습니다! :)

2020-08-10 12:35 UTC, GunHee5719 approved these changes
LGTM:)

2020-08-10 12:50 UTC, merged