feat : Add group, apply
Moong-glE/my-community-backend pull request #46
Opened 2020-08-09 04:19 UTC by RyuJaesang

빨리 안하면 뺏길거같아서 1 : N 설정안하고 칼럼만 대충 지정해놓음
추후 수정할게 
눈에 보이는 거 대충 혼내주라

2020-08-10 11:56 UTC, RyuJaesang commented
7,8번 모델 작성 끝났는데 디비 외래키 칼럼이 참조하는 객체가 or일 수 있어? 찾아봐도 안나와서 일단 주석으로 남겨놨어
@hihiboss @hea9549 @GunHee5719 @als95 @jhcheon1000

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models.py
> +# 이거는 삭제해야하는 거 아닌가...?
삭제해야하는거 맞는데, 다른 파일 머지되면 풀 받아주면 해결 될듯용

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/dept_apply_and_group_apply.py
> +class DeptApplyAndGroupApply(models.Model):
이거 두개 테이블 컬럼 같아도, 다른 파일로 나눠주세요

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/dept_apply_and_group_apply.py
> +        on_delete=models.CASCADE,
리뷰한 사람이 사라져도, 신청 이력이 사라지면 안되므로 SET_NULL이 맞을 것 같습니다.

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/dept_apply_and_group_apply.py
> +    # Or는 뭐지
DeptApply 파일에서는 dept_id를, GroupApply에서는 group_id를 이용해야 한다는 뜻이에요. 파일 나누고 각각 추가해주세요

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/dept_apply_and_group_apply.py
> +        verbose_name='사용자 명단',
`verbose_name=신청 유저` 가 좋을 것 같습니다.

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/dept_apply_and_group_apply.py
> +        on_delete=models.CASCADE,
사라져도 될 것 같긴 한데, 혹시 모르니 신청 이력은 남기는 게 좋을 것 같습니다. SET_NULL로 해주세요.

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/dept_apply_and_group_apply.py
> +    user = models.ForeignKey(
변수명 `user` 보다는, `applier` 같은게 어떨까요?

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/dept_apply_and_group_apply.py
> +        verbose_name='허용 여부',
`허용 여부` 보다는 `수락 여부`가 어떨까 싶습니다.

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/board.py
> +class Board(models.Model):
이거 나중에 충돌날 수 있으니, Board와 Department 부분 모델 머지되면 꼭 풀받아서 올려주세요!

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/group.py
> +        verbose_name="그룹 이름",
그룹 Class 내부이니, 그냥 `'이름'` 만 해둬도 될 것 같습니다.

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/group.py
> +        # 이거 다른애들 False 로 했던데...
이거 회의가 필요하려나? 다른분들 의견에 따라 다를 것 같은데, 개인적으로는 `blank=True`로 둬도 되지 않을까 싶습니다.

2020-08-10 12:22 UTC, GunHee5719 commented on mycomm/models/group.py
> +    managers = models.ForeignKey(
그룹 관리자는 1명이라, OneToOneField로 적용해주세요

2020-08-10 12:23 UTC, GunHee5719 commented
그리고, 풀리퀘 템플릿 등 올라온거 보니 커밋이 많이 꼬인 것 같습니다.  확인해주세요

2020-08-10 13:54 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +class DeptApplyAndGroupApply(models.Model):
재상비 이해하지 못했어요
다시 설명해주세요

2020-08-10 13:54 UTC, RyuJaesang commented on mycomm/models.py
> +# 이거는 삭제해야하는 거 아닌가...?
네 알겠어요

2020-08-10 13:54 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +        on_delete=models.CASCADE,
네 알겠어요

2020-08-10 13:54 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +    # Or는 뭐지
네 알겠어요

2020-08-10 13:55 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +        verbose_name='사용자 명단',
재상비 싫어요
관리자 명단이라는 verbose name이 있어서 사용자 명단이 좋을거 같아요

2020-08-10 13:55 UTC, RyuJaesang commented on mycomm/models/board.py
> +class Board(models.Model):
네 알겠어요

2020-08-10 13:55 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +        verbose_name='허용 여부',
재상비 이건 논의가 필요할 것 같아요

2020-08-10 13:56 UTC, RyuJaesang commented on mycomm/models/group.py
> +        verbose_name="그룹 이름",
네 알겠어요

2020-08-10 13:56 UTC, RyuJaesang commented on mycomm/models/group.py
> +        # 이거 다른애들 False 로 했던데...
재상비 그럴 필요가 있어보여요 천천히 이야기해보아요

2020-08-10 13:56 UTC, RyuJaesang commented
재상비 리베이스 머지해서 올릴게요

2020-08-10 13:57 UTC, RyuJaesang commented on mycomm/models/group.py
> +    managers = models.ForeignKey(
네 알겠어요

2020-08-10 13:58 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +class DeptApplyAndGroupApply(models.Model):
재상비 이해했어요 수정해서 올릴게요

2020-08-10 13:59 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +    user = models.ForeignKey(
재상비 DB specification에 올라온 내용을 토대로 작성했어요

2020-08-10 13:59 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +        on_delete=models.CASCADE,
네 알겠어요

2020-08-10 16:38 UTC, hihiboss requested changes

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models.py
> +# 이거는 삭제해야하는 거 아닌가...?
**request**: 지금 develop에는 없고, 해당 PR에서 생성되었습니다. 삭제해주세요!

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/department.py
>  class Department(models.Model):
**suggestion**: 파이썬 기본 컨벤션이 import 구문들 후에 2줄 띄어쓰기로 알고 있습니다. 이런건 lint를 확인해야할 것 같아요!

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/dept_apply_and_group_apply.py
> +        verbose_name='허용 여부',
**thought**: 신청에 대한 응답이라 저도 수락에 한표!

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/dept_apply_and_group_apply.py
> +        null=False,
**suggestion**: 신청한 후 관리자가 승인하기 전까지 null 일 수 있을듯합니다!

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/dept_apply_and_group_apply.py
> +    user = models.ForeignKey(
**suggestion**: applier가 더 직관적이라고 생각합니다.

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/group.py
> +        # 이거 다른애들 False 로 했던데...
**request**: 이슈 올려주세요!

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/group.py
> +    managers = models.ForeignKey(
**thought**: ForeignKey가 맞습니다. 1명의 유저는 여러 개의 그룹 매니저가 가능하니까요 :)

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/group.py
> +    managers = models.ForeignKey(
**suggestion**: 변수명은 manager로 바꿔주세요.

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/group.py
> +        verbose_name='관리자 명단',
**suggestion**: 관리자 로 바꿔주세요

2020-08-10 16:38 UTC, hihiboss commented on mycomm/models/group.py
> +        on_delete=models.CASCADE,
**suggestion**: 매니저가 삭제되면 group이 삭제된다는 것은 조금 위험한 로직인 것 같습니다. set null 이 맞을 것 같아요!

2020-08-11 10:43 UTC, GunHee5719 commented on mycomm/models/group.py
> +    managers = models.ForeignKey(
@hihiboss 1명의 유저는 1개의 그룹 매니저만 가능한줄 알았는데, 생각해보니 여러 명 해둬도 될 것 같네요. ForeignKey로 두고, 변수명 manager로만 바꿔주세요

2020-08-11 10:43 UTC, GunHee5719 commented on mycomm/models/dept_apply_and_group_apply.py
> +        verbose_name='사용자 명단',
1:N관계에서 유저가 1쪽에 해당되고, 신청자 테이블에서 각 row는 1명의 신청에 대한 값을 저장하므로 `신청 유저` 라는 단수형 표현이 좋을 것 같아요.

2020-08-11 11:40 UTC, hihiboss commented on mycomm/models/group.py
> +    managers = models.ForeignKey(
@GunHee5719 
아 유저는 딱 하나의 그룹매니저만 할 수 있는걸 의도한거였군여 ㅎㅎ

@RyuJaesang 
ForeignKey에 manager로 가시죠~

2020-08-11 12:11 UTC, RyuJaesang commented on mycomm/models/department.py
>  class Department(models.Model):
네 알겠어요

2020-08-11 12:17 UTC, RyuJaesang commented on mycomm/models/dept_apply_and_group_apply.py
> +        verbose_name='사용자 명단',
유저가 어플라이어면 너 말대로 되는 게 맞을 것 같아요
그렇다면 관계 또한 One To One 으로 변경되어야해요

2020-08-11 12:27 UTC, RyuJaesang commented on mycomm/models/group.py
> +        on_delete=models.CASCADE,
만약 매니저가 회원 탈퇴를 통해 삭제될 경우 매니저 권한 위임은 어떻게 되는거죠?

2020-08-11 12:30 UTC, RyuJaesang commented
Conversation들 해결하였습니다. 전에 말했던 대로 Conversation 올리신 분이 resolve 부탁드립니다

2020-08-13 08:08 UTC, GunHee5719 reviewed
Boom!

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/board.py
> +    )
`board.py` 에 왜 수정사항이 있는지 모르겠습니다. 체크해주세요!

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/department.py
> +        verbose_name='이름',
`department.py` 는 이미 머지된 모델이기도 하고, `name` 필드는 `학과 이름` 을, 밑에 `university` 필드는 `학교 이름` 을 나타내기 때문에 `이름`으로 수정할 필요 없어보입니다. 수정사항 반영하지 말아주세요

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/department.py
> +        verbose_name='이름',
만약 수정이 되었으면 좋겠다면, 이 PR과 무관한 모델이므로 다른 PR로 수정 제안하는것이 좋을 것 같습니다.

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +    group_id = models.OneToOneField(
`dept_apply.py` 에서는 `dept_id` 필드로 변수명 지정해주세요.

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +        related_name='reviewer_deptApply'
`related_name = reviewer_dept_apply` 가 맞지 않을까 싶습니다.

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +        related_name='user_deptApply'
snake 표기법 따라주세요

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +        related_name='groupId_deptApply'
snake 표기법 따라주세요

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +    reviewer = models.OneToOneField(
한 명의 유저가 여러 개의 신청 목록을 처리할 수 있으므로, 1대1 관계가 아닐 것 같습니다.

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/group_apply.py
> +    applier = models.OneToOneField(
학과 내 그룹은 한 명의 유저가 여러 개 그룹에 가입 가능하므로 OneToOneField를 이용하시면 안될 것 같습니다.

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/group_apply.py
> +    group_id = models.OneToOneField(
한 그룹에 대해 여러 개의 신청 목록이 생길 수 있으므로 OneToOneField는 적합하지 않을 것 같습니다.

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/group_apply.py
> +    reviewer = models.OneToOneField(
여기도 dept_apply와 같이 적용해주세요

2020-08-13 08:08 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +    applier = models.OneToOneField(
한 유저 당 한 개의 학과에만 가입이 가능하긴 하지만, 편입과 같은 상황에서 만약 해당 학과를 탈퇴하더라도 신청 이력은 남아있기 때문에, 새로운 학과에 가입하는 상황이 생기려면 OneToOneField는 적합하지 않을 것 같습니다.

2020-08-13 17:18 UTC, hihiboss commented on mycomm/models/group.py
> +        # 이거 다른애들 False 로 했던데...
**Request**: @RyuJaesang 주석 지워주세요!

2020-08-13 17:23 UTC, hihiboss commented on mycomm/models/dept_apply.py
> +        # 해당 부분 린트 논의 필요
> @GunHee5719 related_name = reviewer_dept_apply 가 맞지 않을까 싶습니다.

위에 동의하여 주석 제거해도 좋을 것 같습니다.

2020-08-13 17:23 UTC, hihiboss commented on mycomm/models/dept_apply.py
> +        #해당 부분 린트 논의 필요
주석 지워주세요

2020-08-13 17:23 UTC, hihiboss commented on mycomm/models/dept_apply.py
> +        # 해당 부분 린트 논의 필요
주석 지워주세요.

2020-08-13 17:23 UTC, hihiboss commented on mycomm/models/group_apply.py
> +        # 해당 부분 린트 논의 필요
주석 지워주세요.

2020-08-13 17:23 UTC, hihiboss commented on mycomm/models/group_apply.py
> +        #해당 부분 린트 논의 필요
주석 지워주세요.

2020-08-13 17:23 UTC, hihiboss commented on mycomm/models/group_apply.py
> +        # 해당 부분 린트 논의 필요
주석 지워주세요.

2020-08-15 06:50 UTC, RyuJaesang commented on mycomm/models/board.py
> +    )
기존에 띄어쓰기가 있었다가 현재 사라진것 같습니다~

2020-08-15 06:51 UTC, RyuJaesang commented on mycomm/models/department.py
> +        verbose_name='이름',
복원시켰습니다

2020-08-15 07:01 UTC, RyuJaesang commented on mycomm/models/group_apply.py
> +    group_id = models.OneToOneField(
잘 이해가 되지 않는데 한 그룹에 대해 여러개의 신청목록의 예시를 들어줄 수 있을까요?

2020-08-15 07:03 UTC, RyuJaesang commented
건희의 group_apply의 group_id 부분에 대한 설명을 들은 뒤 OneToOne vs ForeignKey만 확정지으면 마무리될 것 같습니다.

2020-08-15 07:18 UTC, GunHee5719 reviewed
여기까지 반영되면 저는approve용~

2020-08-15 07:18 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +    dept_id = models.OneToOneField(
정말 미안한데, 생각해보니 다른 파일들이랑 통일성 위해 `department` 가 맞을 것 같네요.......! id 굳이 언급 안했던거같아서..

2020-08-15 07:18 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +        verbose_name="그룹 아이디",
여기는 `verbose_name='학과'` 로 해주세요. 다른 파일들과 통일성 위해 쌍따옴표가 아닌 따옴표로 부탁합니다~

2020-08-15 07:18 UTC, GunHee5719 commented on mycomm/models/dept_apply.py
> +        related_name='group_id_dept_apply'
dept로 반영해주세요

2020-08-15 07:18 UTC, GunHee5719 commented on mycomm/models/group_apply.py
> +    group_id = models.OneToOneField(
A그룹에 유저 1,2번이 신청하는 경우 group_apply 모델에는 A그룹에 대한 2개 row가 생깁니다. 이는 1:N관계임을 의미합니다.

1:1 관계는 group 모델의 1개 row에 대해서 참조가 1개만 발생해야 합니다!
(ex. 1개 게시글과 1개 설문조사는 1:1관계 <=> article 모델의 1개 row에 대한 참조는 survey에서 1개만 존재)

2020-08-15 07:18 UTC, GunHee5719 commented on mycomm/models/group_apply.py
> +    group_id = models.OneToOneField(
그리고, 여기도 group으로 바꾸는 것을 제안합니다.

2020-08-18 13:20 UTC, jhcheon1000 commented on mycomm/models/dept_apply.py
> +        verbose_name='응답 시간',
'응답 시간'보다는 '응답 일시'가 의미적으로 맞지 않을까용. '응답 시간'은 보통 '응답하는데 걸리는 시간'으로 많이 쓰여서..!

2020-08-18 13:23 UTC, jhcheon1000 commented on mycomm/models/dept_apply.py
> +        null=False,
True로 바꿔주세용.

2020-08-18 13:23 UTC, jhcheon1000 commented on mycomm/models/group_apply.py
> +        null=False,
True!

2020-08-18 13:41 UTC, jhcheon1000 commented on mycomm/models/dept_apply.py
> +        null=False,
True로 바꿔주세요!

2020-08-18 13:43 UTC, jhcheon1000 commented on mycomm/models/group_apply.py
> +        null=False,
얘도 DeptApply와 동일하게!

2020-08-18 13:54 UTC, RyuJaesang commented on mycomm/models/group_apply.py
> +    group_id = models.OneToOneField(
이전에 카톡에서 논의한대로 ManyToMany 로 하겠습니다.

2020-08-18 13:54 UTC, RyuJaesang commented on mycomm/models/dept_apply.py
> +    dept_id = models.OneToOneField(
Group과 마찬가지 맥락으로 ManyToMany Field로 하겠습니다.

2020-08-18 14:24 UTC, RyuJaesang commented
끝 확인좀

2020-08-22 14:34 UTC, hihiboss requested changes

2020-08-22 14:34 UTC, hihiboss commented on mycomm/models/dept_apply.py
> +    department = models.ManyToManyField(
하나의 department에는 여러 개의 dept_apply가 존재할 수 있지만, 하나의 dept_apply에는 여러 개의 deptartment가 존재할 수 없으므로 ForeignKey (1:N 관계)가 적합해보입니다.

2020-08-22 14:34 UTC, hihiboss commented on mycomm/models/group.py
> +    manager = models.ForeignKey(
하나의 그룹에 대해 매니저는 여러명일 수 있고, 하나의 회원은 여러 그룹에 대해 매니저를 할 수 있으므로 ManyToMany 관계가 적합해보입니다.

2020-08-22 14:34 UTC, hihiboss commented on mycomm/models/group_apply.py
> +    group = models.ManyToManyField(
하나의 그룹에 대해 여러 개의 그룹 신청이 존재할 수 있고, 하나의 그룹 신청은 여러 개의 그룹을 가질 수 없으므로 ForeignKey가 적합해보입니다.

2020-08-22 14:34 UTC, hihiboss commented on requirements.txt
> -psycopg2==2.8.5
postgresql 쓰려면 필요합니다!

2020-09-07 12:02 UTC, GunHee5719 approved these changes

2020-09-07 12:02 UTC, hihiboss approved these changes

2020-09-07 12:03 UTC, merged