hotfix/user
Moong-glE/my-community-backend pull request #47
Opened 2020-08-10 16:16 UTC by hihiboss

# Changelist

## fix: User 모델로 어플리케이션 실행할 수 없는 버그 수정
장고 기본 세팅은 models.py 를 모델로 참조합니다. 
그러나 프로젝트에서는 model/user.py와 같이 model 패키지 내의 클래스를 참조하도록 합니다.

따라서 AUTH_USER_MODEL은 mycomm.User 를 참조할 수 없었습니다.
models/__init__.py에 `from .user import *`를 추가하여 참조가 가능하도록 하였습니다.

## chore: PyLint 설정 파일 추가
`.pylintrc`로 pylint 설정 파일 추가하였습니다.
기본 `.pylintrc` 파일에 
```
# CUSTOM
        missing-module-docstring,
        missing-class-docstring,
        unused-wildcard-import,
        wildcard-import
```
추가하였습니다.

## fix: Travis CI 버그 수정
`pylint conf | exit 0` 으로 인한 ci 통과 버그를 수정하였습니다.

## chore: Travis CI 검사 범위 확대
기존 conf 만 검사하던 CI 범위에 mycomm 도 추가하였습니다.

2020-08-11 10:00 UTC, pingoo33 requested changes

2020-08-11 10:00 UTC, pingoo33 commented on requirements.txt
> -django-file-validator==0.0.7
file 크기 제한을 검사하기위해 추가하였습니다.
삭제하지 말아주세요 ㅠㅠ

2020-08-11 10:01 UTC, als95 commented on mycomm/models/user.py
> -        verbose_name='소속 학과',
혹시 '' 대신 ""을 사용하신 이유가 있을까요?
이전 PR에서 얘기를 나누었을 때 둘 모두 string으로 생각되어지며, PEP에서는 별다른 언급이 없어서
''으로 코드 스타일을 통일하자 제안이 있었습니다!

2020-08-11 10:46 UTC, GunHee5719 commented on mycomm/models/user.py
> -        verbose_name='소속 학과',
'으로 통일하는 것이 좋을 것 같습니다.

2020-08-11 10:56 UTC, hihiboss commented on requirements.txt
> -django-file-validator==0.0.7
@als95 

혹시 지금 쓰고 있는 곳이 있나요? 제가 필요한 라이브러리(pillow) pip 인스톨 후에 freeze 한 것 이외로는 수정한게 없어서요!

2020-08-11 10:58 UTC, hihiboss commented on conf/settings/base.py
> -AUTH_USER_MODEL = 'mycomm.User'
@GunHee5719 

settings 파일들의 값들이 전부 ""로 표기되어있어서 ""를 따르겠습니다!

2020-08-11 11:01 UTC, als95 commented on requirements.txt
> -django-file-validator==0.0.7
현재 article_file.py에서 사용하고 있습니다.
file을 upload할 때 크기제한을 하기위해 해놓았습니다.

2020-08-11 11:09 UTC, hihiboss commented on mycomm/models/user.py
> -        verbose_name='소속 학과',
@als95 @GunHee5719 

File watcher에 black이 자동으로 설정되어있었습니다~
수정하겠습니다!

2020-08-11 11:12 UTC, hihiboss commented on requirements.txt
> -django-file-validator==0.0.7
@als95 

import ordering이 어긋난걸로 봐서 requirements.txt에 직접 추가하신거 같은데 virtual env 쓰시면 pip install 후에 freeze 하시면 알아서 requirements.txt에 반영됩니다~

pip로 설치하여 freeze 한 후에 다시 올릴게요!

2020-08-11 11:26 UTC, als95 commented on requirements.txt
> -django-file-validator==0.0.7
아하 그렇군요!
감사합니다.

2020-08-11 11:30 UTC, als95 commented on mycomm/models/user.py
> +        related_name='department_user',
, 가 추가되어 있습니다! 삭제해주세요!

2020-08-11 11:30 UTC, als95 commented on requirements.txt
> +Django==1.9.13
장고 버전이 바뀐것 같은데 괜찮은건가요?

2020-08-11 11:36 UTC, hihiboss commented on mycomm/models/user.py
> +        related_name='department_user',
감사합니다!

2020-08-11 11:36 UTC, hihiboss commented on requirements.txt
> +Django==1.9.13
앗 venv를 안켰네여 ㅠㅠ

이왕 하는김에 3.0.7로 올리겠습니다~

2020-08-13 07:50 UTC, pingoo33 approved these changes

2020-08-13 08:12 UTC, GunHee5719 reviewed
이거만 체크되면 머지되어도 될 것 같습니다.

2020-08-13 08:12 UTC, GunHee5719 commented on mycomm/models/user.py
> +from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
AbstractUser가 AbstractBaseUser를 포괄하는 단위라 AbstractUser를 이용하는 것으로 정한 줄 알았는데, 혹시 변경하신 이유가 있을까요??

2020-08-13 08:12 UTC, GunHee5719 commented on mycomm/models/group.py
> +
아직 PR에서 머지되지 않은 모델이라, 이 부분 수정 반영하지 않아도 될 것 같습니다.

2020-08-13 17:33 UTC, hihiboss commented on mycomm/models/user.py
> +from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
AbstractUser 가 AbstractBaseUser과 PerrmissionMixin을 포함하고 있기 때문입니다!

2020-08-15 07:21 UTC, GunHee5719 approved these changes
LGTM

2020-08-16 07:31 UTC, merged