feat: Implement sign in and sign up
Moong-glE/my-community-backend pull request #53
Opened 2020-08-27 13:43 UTC by als95

## Function description
feat: Implement sign in and sign up

## Code description
Briefly explain your code and technical solution

## Related Issue
None

## Checklist
- [ ] lint
- [ ] build
- [ ] test code

2020-08-27 13:48 UTC, als95 commented
travis 실패는 lint 문제입니다! (후에 수정하도록 하겠습니다.)

우선 user의 가입과 로그인을 view, serializer, manager로 나누어 구현했습니다. 
이게 맞는지 확실하지 않아 많은 리뷰 부탁드립니다. :(

2020-08-30 10:08 UTC, GunHee5719 commented on mycomm/managers/user.py
> +            return ValueError('Users must have a student ID')
`student_id` 는 학과 변경 등의 문제를 고려해서 Nullable로 DB에 지정해뒀습니다. 다만 blank=False로 해뒀기 때문에, nullable과 blank가 모두 false인 `email` 과 다른 방법으로 체크해야 할 것 같습니다.

2020-08-30 10:08 UTC, GunHee5719 commented on mycomm/managers/user.py
> +    def create_user(self, email, student_id, profile_image, is_active, department):
`is_active`는 최초 생성 시 default=true 옵션으로 줄 것이므로, 파라미터로 전달받지 않아도 될 것 같습니다.

2020-08-30 10:08 UTC, GunHee5719 commented on mycomm/managers/user.py
> +            is_active=is_active,
삭제해도 될 것 같습니다.

2020-08-30 10:08 UTC, GunHee5719 commented on mycomm/managers/user.py
> +    def create_user(self, email, student_id, profile_image, is_active, department):
그리고 profile_image와 department는 Nullable하기도 하고, 보통 시나리오에선 이 함수 호출 시 사용되지 않을 것 같아서, 우선은 
`def create_user (self, email, student_id, profile_image=None, department=None)`
로 지정해 두는것이 좋을 것 같습니다.

2020-08-30 10:08 UTC, hea9549 requested changes
로그인은 유저 매니저 쪽에서 말고 rest_auth 의 LoginView를 이용해보세요..!

validation( 유저가 없거나 active가 아니거나 등 validation 은 usermanager말고 serializer에서 검사하는게 맞을듯합니다 ..! rest auth 의 login view, login serializer 등 검색하면 나올듯 해여 )

2020-08-30 10:10 UTC, hea9549 commented
jwt handler쪽도 jwt_serializer 쪽 검색해보면 한번에 처리해주는게 있어여
sign_in.py , sign_up.py 도 auth.py로 하나 파일로 통일후 함수 두개로 처리해주세요 너무 세분화된 것 같아요!

2020-08-31 01:47 UTC, als95 commented on mycomm/managers/user.py
> +            is_active=is_active,
normalize_email을 삭제해도 될 것 같다는 말씀이신가요??

2020-08-31 04:52 UTC, GunHee5719 commented on mycomm/managers/user.py
> +            is_active=is_active,
@als95 아뇨 is_active를 삭제해도 model에서 default를 지정해뒀기 때문에, 인자전달이 필요 없다는 의미였습니다!

2020-08-31 04:53 UTC, als95 commented on mycomm/managers/user.py
> +            is_active=is_active,
아하 넵 알겠습니다! :)

2020-08-31 10:30 UTC, als95 commented on mycomm/managers/user.py
> +            return ValueError('Users must have a student ID')
수정하였습니다!
(UserManager 사용하지 않고 serializer에서 validation을 진행하였습니다.)

2020-08-31 10:30 UTC, als95 commented on mycomm/managers/user.py
> +    def create_user(self, email, student_id, profile_image, is_active, department):
수정하였습니다!
(해당 부분은 serializer에서 진행하였습니다.)

2020-08-31 10:30 UTC, als95 commented on mycomm/managers/user.py
> +            is_active=is_active,
삭제하였습니다.

2020-09-07 11:56 UTC, hea9549 approved these changes

2020-09-07 11:57 UTC, merged