feat: contribution guide
Moong-glE/my-community-backend pull request #7
Opened 2020-05-03 13:30 UTC by RyuJaesang

#5 upload CONTRIBUTING.md

2020-05-03 13:32 UTC, GunHee5719 reviewed
:(

2020-05-03 13:32 UTC, GunHee5719 commented on CONTRIBUTING.md
> +We **_prefer English over Korean_** due to its globally high usage and impact. So it is strongly recommended to use English throughout your development routine. Don't worry about your bad English. We
I prefer Korean over English

2020-05-03 13:34 UTC, GunHee5719 commented on CONTRIBUTING.md
> +
풀리퀘 가이드도 추가해주세용

2020-05-03 13:36 UTC, hea9549 commented
풀리퀘 가이드랑 풀리퀘 템플릿도 추가해주시면 좋을듯여!

2020-05-03 14:22 UTC, RyuJaesang commented
Pull_request_template 확인 부탁드려요~

2020-05-03 14:22 UTC, RyuJaesang commented on CONTRIBUTING.md
> +We **_prefer English over Korean_** due to its globally high usage and impact. So it is strongly recommended to use English throughout your development routine. Don't worry about your bad English. We
Modified~!

2020-05-03 14:38 UTC, hea9549 requested changes
When everything is done, merge the commits into one or two.

2020-05-03 14:38 UTC, hea9549 commented on CONTRIBUTING.md
> +Keep your codes clean and consistent using code formatters and linters. Most of the time formatting and linting would already have been set by default in each repository. And sometimes you should use
`Keep your codes clean and consistent using code formatters and linters. Most of the time formatting and linting would already have been set by default in each repository. And sometimes you should use the specific code editor to match the configuration.` 
Is too generalized.

`Keep your codes clean and consistent using code formatters and linters. we prefer to use basic PEP8 format.` seems to be appropriate for our project

2020-05-03 14:38 UTC, hea9549 commented on PULL_REQUEST_TEMPLATE.md
> +- [x] plz
how about add 
+ Write test code
+ Test code execution
+ All Python code must be 100% pep8 and isort clean.

it just example.

2020-05-03 14:45 UTC, RyuJaesang commented on PULL_REQUEST_TEMPLATE.md
> +- [x] plz
Let's discuss with other members

2020-05-03 14:51 UTC, hea9549 commented on CONTRIBUTING.md
> +**Examples**
두가지 커밋타입이 혼재되어있음!

둘중하나 지우고 하나로 택해야하는데 나는 전자스타일
- `chore: add Oyster build script`
- `docs: explain hat wobble`

선호함
@RyuJaesang @GunHee5719 @jhcheon1000

2020-05-03 14:51 UTC, hea9549 approved these changes

2020-05-03 14:52 UTC, hea9549 requested changes
잘못누름  request change.

2020-05-03 14:53 UTC, hea9549 commented on CONTRIBUTING.md
> +Refer to [here](http://karma-runner.github.io/0.10/dev/git-commit-msg.html) and [here](https://seesparkbox.com/foundry/semantic_commit_messages) for more information.
그래서 이거는 그냥 contribution guide에대한 설명이라 
`Generally there are two acceptable styles of commit message.`
이거랑
`Refer to [here](http://karma-runner.github.io/0.10/dev/git-commit-msg.html) and [here](https://seesparkbox.com/foundry/semantic_commit_messages) for more information.`
이거는 지워줘도될듯

2020-05-03 14:53 UTC, hea9549 approved these changes

2020-05-03 15:05 UTC, RyuJaesang commented
We should discuss about the 
@hea9549 @GunHee5719 @jhcheon1000

2020-05-03 15:08 UTC, hea9549 commented on PULL_REQUEST_TEMPLATE.md
> +- [x] plz
추가할만한거없으면 기본적으로 저거만 반영하고

나중에 추후 필요시 새로 이슈파서해도될듯

2020-05-03 15:29 UTC, GunHee5719 commented on CONTRIBUTING.md
> +**Examples**
나도 전자 선호 깰꿈쓰

2020-05-03 15:36 UTC, GunHee5719 commented on PULL_REQUEST_TEMPLATE/bug-template.md
> +## Bug description
이거 앞에 Related Issue 추가해서 풀리퀘에서 issue 연결해주면 좋을거같아용~ 밑에 feature-template에도

2020-05-03 15:36 UTC, GunHee5719 commented
아 그리고 Docs용 풀리퀘 가이드도 있으면 좋을거 같은데 어떤가요

@hea9549 @jhcheon1000 @RyuJaesang

2020-05-11 08:08 UTC, RyuJaesang commented on CONTRIBUTING.md
> +
추가해써용~

2020-05-11 08:08 UTC, RyuJaesang commented on PULL_REQUEST_TEMPLATE/feature-template.md
> +## Is there any checklist?
선생님들 여기 확인좀 해주세요
@hea9549 @GunHee5719 @jhcheon1000

2020-05-11 08:09 UTC, GunHee5719 approved these changes
LGTM:)

2020-06-16 07:17 UTC, hihiboss commented on CONTRIBUTING.md
> +Please follow these guidelines when you are trying to contribute to MCIP software.
```suggestion
Please follow these guidelines when you are trying to contribute to **My Community** software.
```

2020-06-16 07:17 UTC, hihiboss commented on CONTRIBUTING.md
> +We **_prefer English and Korean_** due to all of our team member is Korean, we prefer Korean. So it is strongly recommended to use Korean. But it needs to conversate in gobally, we also prefer the En
```suggestion
We **_prefer English and Korean_** due to all of our team member is Korean, we prefer Korean. So it is strongly recommended to use Korean. But it needs to conversate in globally, we also prefer the English.
```

2020-06-16 07:17 UTC, hihiboss commented on CONTRIBUTING.md
> +**Examples**
나도 전자

2020-06-16 07:17 UTC, hihiboss commented on CONTRIBUTING.md
> +**Examples**
그리고 나는 개인적으로 커밋타입 너무 많은거 비추함
너무 많으면 어떤거 써야할지도 잘 모르고 중구난방되는 느낌이라??
`style` 요런 타입도 `chore` 같은 타입으로 대체할 수 있다고 생각함

`chore`, `feat`, `fix`, `refactor`, `test` 정도로 나는 추천!

2020-06-16 07:17 UTC, hihiboss commented on CONTRIBUTING.md
> +**Examples**
여기 다 대문자로 고쳐주세요!

예) `chore: Add Oyster build script`

2020-06-16 07:17 UTC, hihiboss commented on CONTRIBUTING.md
> +- `Update README.md`
여기 앞에 타입 붙여주시죠!

예) `chore: Update README.md`

2020-06-16 07:17 UTC, hihiboss commented on CONTRIBUTING.md
> +- `Function description
```suggestion
- `Function description`
```

2020-06-16 07:17 UTC, hihiboss commented on PULL_REQUEST_TEMPLATE/feature-template.md
> +## Is there any checklist?
[ ] lint
[ ] build
[ ] test code

생각나는건 요정도?

2020-07-05 07:40 UTC, RyuJaesang commented on CONTRIBUTING.md
> +**Examples**
chore, feat, fix, refactor, test, docs 총 6개로 땅땅

2020-07-05 07:44 UTC, RyuJaesang commented
위 사항들 전부 수정한뒤 끝나고 커밋하께요~

2020-07-06 12:00 UTC, RyuJaesang commented
커밋했습니다 추가적인 변경사항 없으면 머지합니다
@hea9549 @GunHee5719 @hihiboss @als95 @jhcheon1000

2020-07-06 13:23 UTC, merged